services:
  app:
    image: node:18
    working_dir: /app
    command: >
      sh -c "npm install && 
             npm run serve"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
